// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeeklyActivityTracker.Data.WeeklyTarget;

#nullable disable

namespace WeeklyActivityTracker.WeeklyTargetAPI.InitDatabase.Migrations
{
    [DbContext(typeof(WeeklyTargetDbContext))]
    partial class WeeklyTargetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeeklyActivityTracker.Models.WeeklyTarget.WeeklyTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TargetCompleteByTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TargetCompletedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TargetCreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetDecription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeeklyTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
